#include <bits/stdc++.h>
using namespace std;struct E{long long t;double S,o;int d;};struct Q{bool done=0,cens=0,deep=0,hedged=0,hedge_done=0;int n=0;double f[3]={};double base=0,hedgep=0,hedge_entry=0;int hedge_outcome=0;};
static inline int d2(const char*p){return(p[0]-48)*10+p[1]-48;}static inline int d3(const char*p){return(p[0]-48)*100+(p[1]-48)*10+p[2]-48;}static inline int dbm(int m){static int a[]={0,0,31,60,91,121,152,182,213,244,274,305,335};return a[m];}static inline long long parseT(const string&s,bool ms){int mo=d2(s.data()+5),d=d2(s.data()+8),H=d2(s.data()+11),M=d2(s.data()+14),se=d2(s.data()+17),x=ms?d3(s.data()+20):0;return((long long)(dbm(mo)+d-1)*86400+H*3600+M*60+se)*1000+x;}static inline double fld(const char*&p){if(*p=='\t'){++p;return NAN;}char*e;double v=strtod(p,&e);p=e;if(*p=='\t')++p;return v;}static inline void qp(const string&s,double&b,double&a){const char*p=s.c_str()+24;double x=fld(p),y=fld(p);if(isfinite(x))b=x;if(isfinite(y))a=y;}static vector<string>cv(const string&s){vector<string>v;size_t q=0;for(size_t i=0;i<=s.size();i++)if(i==s.size()||s[i]==','){v.push_back(s.substr(q,i-q));q=i+1;}return v;}static inline bool mb(const vector<long long>&v,long long a,long long b){auto it=upper_bound(v.begin(),v.end(),a);return it!=v.end()&&*it<b;}static inline double bp(const Q&q,int d,double px){double z=0;for(int i=0;i<q.n;i++)z+=d*(px-q.f[i]);return z;}
int main(){vector<E>ev;{ifstream f("/mnt/data/fresh648_events.csv");string l;getline(f,l);while(getline(f,l)){auto a=cv(l);ev.push_back({parseT(a[0],false),stod(a[2]),stod(a[3]),stoi(a[4])});}}vector<long long>m1;{ifstream f("/mnt/data/GOLD#_M1_202201030100_202608282357(5).csv");string l;getline(f,l);while(getline(f,l)){if(l.size()<20||l.compare(0,4,"2024"))continue;m1.push_back(parseT(l,false));}}vector<Q>q(ev.size());size_t next=0;vector<int>act;double bid=NAN,ask=NAN;long long prev=-1;vector<string>fs;for(auto&p:filesystem::directory_iterator("/mnt/data/ticks2024"))fs.push_back(p.path().string());sort(fs.begin(),fs.end());
 for(auto&fn:fs){ifstream f(fn);string l;getline(f,l);while(getline(f,l)){if(l.size()<25)continue;long long t=parseT(l,true);qp(l,bid,ask);if(!isfinite(bid)||!isfinite(ask))continue;if(prev>=0&&t-prev>120000&&mb(m1,prev,t)){for(int i:act)q[i].done=q[i].cens=true;act.clear();}
 while(next<ev.size()&&ev[next].t<=t){int i=next++;if(mb(m1,ev[i].t,t))q[i].done=q[i].cens=true;else{q[i].n=1;q[i].f[0]=ev[i].d>0?ask:bid;act.push_back(i);}}
 size_t wr=0;for(int i:act){auto&E=ev[i];auto&x=q[i];int d=E.d;double ex=d>0?bid:ask,ad=d>0?ask:bid,xe=d*(ex-E.o)/E.S,xa=d*(ad-E.o)/E.S;
   if(xe<=-1.2){x.base=bp(x,d,ex); if(x.hedged&&!x.hedge_done){int hd=-d;double hexit=hd>0?bid:ask;x.hedgep+=hd*(hexit-x.hedge_entry);x.hedge_done=true;x.hedge_outcome=2;}x.done=true;continue;}
   while(x.n<3){double lv=-.4*x.n;if(xa<=lv){x.f[x.n]=ad;x.n++;if(x.n==3)x.deep=true;}else break;}
   if(x.deep&&!x.hedged&&xe<=-1.0){int hd=-d;x.hedge_entry=hd>0?ask:bid; // open opposite: buy uses ask, short uses bid
      x.hedged=true;}
   if(x.hedged&&!x.hedge_done&&xe>=-.8){int hd=-d;double hexit=hd>0?bid:ask;x.hedgep+=hd*(hexit-x.hedge_entry);x.hedge_done=true;x.hedge_outcome=1;}
   if(x.n>=2){double be=0;for(int k=0;k<x.n;k++)be+=x.f[k];be/=x.n;if((d>0&&bid>=be)||(d<0&&ask<=be)){x.base=bp(x,d,ex);if(x.hedged&&!x.hedge_done){int hd=-d;double hexit=hd>0?bid:ask;x.hedgep+=hd*(hexit-x.hedge_entry);x.hedge_done=true;x.hedge_outcome=3;}x.done=true;continue;}}
   else if(xe>=1){x.base=bp(x,d,ex);x.done=true;continue;}
   act[wr++]=i;
 }act.resize(wr);prev=t;}}
 for(auto&x:q)if(!x.done)x.done=x.cens=true;
 int comp=0,cen=0,trig=0,reb=0,hard=0;double sb=0,sh=0,delta=0;vector<double>ds;for(auto&x:q){if(x.cens){cen++;continue;}comp++;sb+=x.base;sh+=x.base+x.hedgep;delta+=x.hedgep;if(x.hedged){trig++;ds.push_back(x.hedgep);if(x.hedge_outcome==1)reb++;if(x.hedge_outcome==2)hard++;}}
 cout<<"completed="<<comp<<" cens="<<cen<<" hedge_trigger="<<trig<<" rebound_stop="<<reb<<" hard_close="<<hard<<"\n";cout<<"base_mean="<<sb/comp<<" hedge_mean="<<sh/comp<<" delta_mean_all="<<delta/comp<<" delta_total="<<delta<<"\n";if(trig){double s=accumulate(ds.begin(),ds.end(),0.0);sort(ds.begin(),ds.end());cout<<"hedge_avg_when_triggered="<<s/trig<<" median="<<ds[ds.size()/2]<<" worst="<<ds.front()<<" best="<<ds.back()<<"\n";}
 ofstream o("/mnt/data/deep_hedge_detail.csv");o<<"event,censored,base,hedge_pnl,total,triggered,outcome\n";for(size_t i=0;i<q.size();i++)o<<i<<","<<q[i].cens<<","<<q[i].base<<","<<q[i].hedgep<<","<<q[i].base+q[i].hedgep<<","<<q[i].hedged<<","<<q[i].hedge_outcome<<"\n";
}
