import pandas as pd, numpy as np, json
from pathlib import Path
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
import argparse
ap=argparse.ArgumentParser();ap.add_argument('--universe',required=True);ap.add_argument('--out-dir',required=True);args=ap.parse_args()
outdir=Path(args.out_dir);outdir.mkdir(parents=True,exist_ok=True)
D=pd.read_csv(args.universe,parse_dates=['decision'])
features=['k','stop_dist_atr','fast_body_rng','std_align','std_body_rng','slow_align','adx28_rel','di14_signed','ema8_21_signed','path_eff4_rel','path_eff12_rel','flip8']
for tf in ('m15','m30','h1'):features += [f'{tf}_{x}' for x in ['aligned','streak','body_sum_atr','body_rng','opp_wick']]
heads=[('RUNWAY','early3',None),('WIN','win',None),('PERSIST','next_same',None),('SEVERE','severe',None),('STOP','stop_hit',None),('SHOCK','shock',1)]
HEAD_C={'RUNWAY':0.5,'WIN':0.02,'PERSIST':0.05,'SEVERE':0.2,'STOP':1.0,'SHOCK':0.02}
policies=['RUNWAY','RUNWAY_PERSIST','RUNWAY_WIN_PERSIST','RUNWAY_SAFE_PERSIST']

def fit(df,H,label,stage):
 x=df[df.k==stage] if stage else df
 p=make_pipeline(StandardScaler(),LogisticRegression(C=HEAD_C[H],max_iter=3000));p.fit(x[features],x[label]);return p,x

def pred(m,df):return m.predict_proba(df[features])[:,1]
# eras: year -> prior training years; FUTURE -> all available
train_specs=[('2023',D[D.year<2023]),('2024',D[D.year<2024]),('2025',D[D.year<2025]),('2026',D[D.year<2026]),('FUTURE',D)]
export={'features':features,'eras':{},'policies':policies}
metrics=[]
for era,tr in train_specs:
 E={}
 pipes={}
 for H,label,stage in heads:
  p,x=fit(tr,H,label,stage);pipes[H]=p;sc=p.named_steps['standardscaler'];lr=p.named_steps['logisticregression']
  E[H]={'mean':sc.mean_.tolist(),'scale':sc.scale_.tolist(),'coef':lr.coef_[0].tolist(),'intercept':float(lr.intercept_[0]),'train_n':len(x),'positive':int(x[label].sum())}
  if era!='FUTURE':
   y=int(era);te=D[D.year==y];tev=te[te.k==stage] if stage else te
   if len(tev) and tev[label].nunique()>1:metrics.append({'era':era,'head':H,'eval_n':len(tev),'auc':roc_auc_score(tev[label],pred(p,tev)),'prevalence':tev[label].mean()})
 # thresholds from prior training score distributions
 pr={H:pred(pipes[H],tr if H!='SHOCK' else tr[tr.k==1]) for H in pipes}
 # full-row arrays for common heads
 r=pred(pipes['RUNWAY'],tr);w=pred(pipes['WIN'],tr);ps=pred(pipes['PERSIST'],tr);sev=pred(pipes['SEVERE'],tr)
 ks=tr.k.to_numpy();
 scoremap={
  'RUNWAY':r,
  'RUNWAY_PERSIST':r*np.where(ks>=2,ps,1.0),
  'RUNWAY_WIN_PERSIST':r*w*np.where(ks>=2,ps,1.0),
  'RUNWAY_SAFE_PERSIST':r*(1-sev)*np.where(ks>=2,ps,1.0),
 }
 E['THRESHOLDS']={name:{'q50':float(np.quantile(v,.5)),'q75':float(np.quantile(v,.75))} for name,v in scoremap.items()}
 E['THRESHOLDS']['shock_q95']=float(np.quantile(pr['SHOCK'],.95))
 export['eras'][era]=E
(outdir/'V10_LIVE_MODEL_EXPORT_R2.json').write_text(json.dumps(export,indent=2),encoding='utf-8')
pd.DataFrame(metrics).to_csv(outdir/'V10_LIVE_MODEL_METRICS_R2.csv',index=False)
# generate MQH
out=[]
out += ['// AUTO-GENERATED by train_v10_live_ml.py -- DO NOT HAND EDIT','#ifndef V10_LIVE_ML_MODELS_R2_MQH','#define V10_LIVE_ML_MODELS_R2_MQH','',f'#define V10ML_FEATURES {len(features)}',f'#define V10ML_ERAS {len(train_specs)}',f'#define V10ML_HEADS {len(heads)}',f'#define V10ML_POLICIES {len(policies)}','']
out.append('enum V10MLEra { V10_ERA_2023=0, V10_ERA_2024=1, V10_ERA_2025=2, V10_ERA_2026=3, V10_ERA_FUTURE=4 };')
out.append('enum V10MLHead { V10_HEAD_RUNWAY=0, V10_HEAD_WIN=1, V10_HEAD_PERSIST=2, V10_HEAD_SEVERE=3, V10_HEAD_STOP=4, V10_HEAD_SHOCK=5 };')
out.append('enum V10MLPolicy { V10_POLICY_RUNWAY=0, V10_POLICY_RUNWAY_PERSIST=1, V10_POLICY_RUNWAY_WIN_PERSIST=2, V10_POLICY_RUNWAY_SAFE_PERSIST=3 };')
out.append('')
out.append('const string V10ML_FEATURE_NAMES[V10ML_FEATURES] = {'+','.join('"'+x+'"' for x in features)+'};')
# 3d arrays era,head,feat
for arrname,key in [('MEAN','mean'),('SCALE','scale'),('COEF','coef')]:
 out.append(f'const double V10ML_{arrname}[V10ML_ERAS][V10ML_HEADS][V10ML_FEATURES] = {{')
 for ei,(era,tr) in enumerate(train_specs):
  out.append(' {')
  for hi,(H,label,stage) in enumerate(heads):
   vals=export['eras'][era][H][key]; out.append('  {'+','.join(f'{v:.17g}' for v in vals)+'}'+(',' if hi<len(heads)-1 else ''))
  out.append(' }'+(',' if ei<len(train_specs)-1 else ''))
 out.append('};\n')
out.append('const double V10ML_INTERCEPT[V10ML_ERAS][V10ML_HEADS] = {')
for ei,(era,tr) in enumerate(train_specs):
 vals=[export['eras'][era][H]['intercept'] for H,_,__ in heads];out.append(' {'+','.join(f'{v:.17g}' for v in vals)+'}'+(',' if ei<len(train_specs)-1 else ''))
out.append('};\n')
out.append('const double V10ML_Q50[V10ML_ERAS][V10ML_POLICIES] = {')
for ei,(era,tr) in enumerate(train_specs):
 vals=[export['eras'][era]['THRESHOLDS'][p]['q50'] for p in policies];out.append(' {'+','.join(f'{v:.17g}' for v in vals)+'}'+(',' if ei<len(train_specs)-1 else ''))
out.append('};')
out.append('const double V10ML_Q75[V10ML_ERAS][V10ML_POLICIES] = {')
for ei,(era,tr) in enumerate(train_specs):
 vals=[export['eras'][era]['THRESHOLDS'][p]['q75'] for p in policies];out.append(' {'+','.join(f'{v:.17g}' for v in vals)+'}'+(',' if ei<len(train_specs)-1 else ''))
out.append('};')
out.append('const double V10ML_SHOCK_Q95[V10ML_ERAS] = {'+','.join(f"{export['eras'][era]['THRESHOLDS']['shock_q95']:.17g}" for era,_ in train_specs)+'};')
out += ['','double V10MLSigmoid(double z){ if(z>35.0) z=35.0; if(z<-35.0) z=-35.0; return 1.0/(1.0+MathExp(-z)); }','double V10MLPredict(const V10MLEra era,const V10MLHead head,const double &x[]){ double z=V10ML_INTERCEPT[(int)era][(int)head]; for(int i=0;i<V10ML_FEATURES;i++){ double s=V10ML_SCALE[(int)era][(int)head][i]; if(MathAbs(s)<1e-12) s=1.0; z += V10ML_COEF[(int)era][(int)head][i]*((x[i]-V10ML_MEAN[(int)era][(int)head][i])/s); } return V10MLSigmoid(z); }','V10MLEra V10MLEraForTime(datetime t){ MqlDateTime d; TimeToStruct(t,d); if(d.year<=2023) return V10_ERA_2023; if(d.year==2024) return V10_ERA_2024; if(d.year==2025) return V10_ERA_2025; if(d.year==2026) return V10_ERA_2026; return V10_ERA_FUTURE; }','','#endif']
(outdir/'V10LiveMLModelsR2.mqh').write_text('\n'.join(out)+'\n',encoding='utf-8')
print(pd.DataFrame(metrics).pivot(index='head',columns='era',values='auc').round(3))
print('features',len(features),'mqh bytes',(outdir/'V10LiveMLModelsR2.mqh').stat().st_size)
