#include <bits/stdc++.h>
using namespace std;struct E{long long t;double S;int d;string ts;};struct St{bool done=0,cens=0,cp=0,r2=0;double ep=0,pnl=0;string cat;long long endt=0;};
static inline int d2(const char*p){return (p[0]-'0')*10+p[1]-'0';}static inline int d3(const char*p){return (p[0]-'0')*100+(p[1]-'0')*10+p[2]-'0';}static inline int dbm(int m){static int a[]={0,0,31,60,91,121,152,182,213,244,274,305,335};return a[m];}static long long tt(const string&s){int mo=d2(s.data()+5),da=d2(s.data()+8),H=d2(s.data()+11),M=d2(s.data()+14),S=d2(s.data()+17),ms=d3(s.data()+20);return ((long long)(dbm(mo)+da-1)*86400+H*3600+M*60+S)*1000+ms;}static long long ti(const string&s){int mo=d2(s.data()+5),da=d2(s.data()+8),H=d2(s.data()+11),M=d2(s.data()+14),S=d2(s.data()+17);return ((long long)(dbm(mo)+da-1)*86400+H*3600+M*60+S)*1000;}
static inline double fd(const char*&p){if(*p=='\t'){++p;return NAN;}char*e;double v=strtod(p,&e);p=e;if(*p=='\t')++p;return v;}static inline void pq(const string&s,double&b,double&a){const char*p=s.c_str()+24;double x=fd(p),y=fd(p);if(isfinite(x))b=x;if(isfinite(y))a=y;}static vector<string> csv(const string&s){vector<string>v;size_t st=0;for(size_t i=0;i<=s.size();++i)if(i==s.size()||s[i]==','){v.push_back(s.substr(st,i-st));st=i+1;}return v;}static inline bool m1b(const vector<long long>&v,long long a,long long b){auto it=upper_bound(v.begin(),v.end(),a);return it!=v.end()&&*it<b;}
int main(int ac,char**av){string ev=ac>1?av[1]:"/mnt/data/runner_union_2024.csv";string out=ac>2?av[2]:"/mnt/data/floor_runner_tick.csv";vector<E>e;{ifstream f(ev);string l;getline(f,l);while(getline(f,l)){auto a=csv(l);e.push_back({ti(a[0]),stod(a[1]),stoi(a[3]),a[0]});}}sort(e.begin(),e.end(),[](auto&a,auto&b){return a.t<b.t;});vector<long long>m1;{ifstream f("/mnt/data/GOLD#_M1_202201030100_202608282357(5).csv");string l;getline(f,l);while(getline(f,l)){if(l.size()<20||l.compare(0,4,"2024"))continue;int mo=d2(l.data()+5),da=d2(l.data()+8),H=d2(l.data()+11),M=d2(l.data()+14),S=d2(l.data()+17);m1.push_back(((long long)(dbm(mo)+da-1)*86400+H*3600+M*60+S)*1000);}}
 vector<St>s(e.size());vector<int>a;size_t nx=0;double bid=NAN,ask=NAN;long long prev=-1;vector<string>files;for(auto&p:filesystem::directory_iterator("/mnt/data/ticks2024"))files.push_back(p.path().string());sort(files.begin(),files.end());for(auto&fn:files){ifstream f(fn);string l;getline(f,l);while(getline(f,l)){if(l.size()<25)continue;long long t=tt(l);pq(l,bid,ask);if(!isfinite(bid)||!isfinite(ask))continue;if(prev>=0&&t-prev>120000&&m1b(m1,prev,t)){for(int id:a)if(!s[id].done){s[id].done=s[id].cens=1;s[id].cat="GAP";}a.clear();}
 while(nx<e.size()&&e[nx].t<=t){if(m1b(m1,e[nx].t,t)){s[nx].done=s[nx].cens=1;s[nx].cat="START_GAP";}else{s[nx].ep=e[nx].d>0?ask:bid;a.push_back(nx);}nx++;}
 size_t w=0;for(int id:a){auto&q=s[id];auto&E=e[id];if(q.done)continue;double ex=E.d>0?bid:ask;double R=.25*E.S;double rr=E.d*(ex-q.ep)/R;if(!q.cp){if(rr<=-1){q.pnl=rr;q.done=1;q.cat="SL";q.endt=t;continue;}if(rr>=1){q.cp=1;}else if(t-E.t>=15*60000LL){q.pnl=rr;q.done=1;q.cat="TIMEOUT15";q.endt=t;continue;}}
 if(q.cp){if(rr<=.5){q.pnl=rr;q.done=1;q.cat="FLOOR05";q.endt=t;continue;}if(rr>=2){q.pnl=rr;q.r2=1;q.done=1;q.cat="RUNNER2";q.endt=t;continue;}if(t-E.t>=60*60000LL){q.pnl=rr;q.done=1;q.cat="TIMEOUT60";q.endt=t;continue;}}
 a[w++]=id;}a.resize(w);prev=t;}}
 for(auto&q:s)if(!q.done){q.done=q.cens=1;q.cat="END";}double sum=0,pos=0,neg=0;int cen=0,win=0,loss=0,flat=0,cp=0,r2=0;double worst=0;for(auto&q:s){if(q.cens){cen++;continue;}sum+=q.pnl;if(q.cp)cp++;if(q.r2)r2++;if(q.pnl>1e-12){win++;pos+=q.pnl;}else if(q.pnl<-1e-12){loss++;neg+=q.pnl;}else flat++;worst=min(worst,q.pnl);}int comp=win+loss+flat;cout<<"N,"<<e.size()<<"\ncompleted,"<<comp<<"\ncensored,"<<cen<<"\nwins,"<<win<<"\nlosses,"<<loss<<"\nWR_positive,"<<(comp?double(win)/comp:NAN)<<"\nmean_R,"<<(comp?sum/comp:NAN)<<"\ntotal_R,"<<sum<<"\nPF,"<<(neg<0?pos/-neg:NAN)<<"\navg_pos_R,"<<(win?pos/win:0)<<"\navg_neg_R,"<<(loss?neg/loss:0)<<"\ncheckpoint,"<<cp<<"\nrunner2,"<<r2<<"\nrunner2_given_cp,"<<(cp?double(r2)/cp:NAN)<<"\nworst_R,"<<worst<<"\n";ofstream o(out);o<<"decision,S,dir,entry,cat,pnlR,cp,r2,censored\n";for(size_t i=0;i<e.size();i++)o<<e[i].ts<<","<<e[i].S<<","<<e[i].d<<","<<s[i].ep<<","<<s[i].cat<<","<<s[i].pnl<<","<<s[i].cp<<","<<s[i].r2<<","<<s[i].cens<<"\n";}
