#include <bits/stdc++.h>
using namespace std;struct E{long long t;double S;int d;string ts;};struct St{bool started=0,done=0,cens=0,cp=0,be=0,sl=0,to15=0,to60=0;double ep=0,cp_rr=0,max_rr=-1e9,end_rr=0;long long cpt=0,endt=0;};
static inline int d2(const char*p){return (p[0]-'0')*10+p[1]-'0';} static inline int d3(const char*p){return (p[0]-'0')*100+(p[1]-'0')*10+p[2]-'0';} static inline int dbm(int m){static int a[]={0,0,31,60,91,121,152,182,213,244,274,305,335};return a[m];}
static long long tt(const string&s){int mo=d2(s.data()+5),da=d2(s.data()+8),H=d2(s.data()+11),M=d2(s.data()+14),S=d2(s.data()+17),ms=d3(s.data()+20);return ((long long)(dbm(mo)+da-1)*86400+H*3600+M*60+S)*1000+ms;}static long long ti(const string&s){int mo=d2(s.data()+5),da=d2(s.data()+8),H=d2(s.data()+11),M=d2(s.data()+14),S=d2(s.data()+17);return ((long long)(dbm(mo)+da-1)*86400+H*3600+M*60+S)*1000;}
static inline double fd(const char*&p){if(*p=='\t'){++p;return NAN;}char*e;double v=strtod(p,&e);p=e;if(*p=='\t')++p;return v;}static inline void pq(const string&s,double&b,double&a){const char*p=s.c_str()+24;double x=fd(p),y=fd(p);if(isfinite(x))b=x;if(isfinite(y))a=y;}static vector<string>csv(const string&s){vector<string>v;size_t st=0;for(size_t i=0;i<=s.size();++i)if(i==s.size()||s[i]==','){v.push_back(s.substr(st,i-st));st=i+1;}return v;}static inline bool m1b(const vector<long long>&v,long long a,long long b){auto it=upper_bound(v.begin(),v.end(),a);return it!=v.end()&&*it<b;}
int main(){vector<E>e;{ifstream f("/mnt/data/runner_union_2024.csv");string l;getline(f,l);while(getline(f,l)){auto a=csv(l);e.push_back({ti(a[0]),stod(a[1]),stoi(a[3]),a[0]});}}sort(e.begin(),e.end(),[](auto&a,auto&b){return a.t<b.t;});vector<long long>m1;{ifstream f("/mnt/data/GOLD#_M1_202201030100_202608282357(5).csv");string l;getline(f,l);while(getline(f,l)){if(l.size()<20||l.compare(0,4,"2024"))continue;int mo=d2(l.data()+5),da=d2(l.data()+8),H=d2(l.data()+11),M=d2(l.data()+14),S=d2(l.data()+17);m1.push_back(((long long)(dbm(mo)+da-1)*86400+H*3600+M*60+S)*1000);}}
 vector<St>s(e.size());vector<int>aidx;size_t nx=0;double bid=NAN,ask=NAN;long long prev=-1;vector<string>files;for(auto&p:filesystem::directory_iterator("/mnt/data/ticks2024"))files.push_back(p.path().string());sort(files.begin(),files.end());
 for(auto&fn:files){ifstream f(fn);string l;getline(f,l);while(getline(f,l)){if(l.size()<25)continue;long long t=tt(l);pq(l,bid,ask);if(!isfinite(bid)||!isfinite(ask))continue;if(prev>=0&&t-prev>120000&&m1b(m1,prev,t)){for(int id:aidx)if(!s[id].done){s[id].done=s[id].cens=1;s[id].endt=prev;}aidx.clear();}
 while(nx<e.size()&&e[nx].t<=t){if(m1b(m1,e[nx].t,t)){s[nx].done=s[nx].cens=1;}else{s[nx].started=1;s[nx].ep=e[nx].d>0?ask:bid;aidx.push_back(nx);}nx++;}
 size_t w=0;for(int id:aidx){auto&q=s[id];auto&E=e[id];if(q.done)continue;double ex=E.d>0?bid:ask;double R=.25*E.S;double rr=E.d*(ex-q.ep)/R;
   if(!q.cp){if(rr<=-1){q.sl=1;q.end_rr=rr;q.done=1;q.endt=t;continue;}if(rr>=1){q.cp=1;q.cp_rr=rr;q.cpt=t;q.max_rr=rr;}else if(t-E.t>=15*60000LL){q.to15=1;q.end_rr=rr;q.done=1;q.endt=t;continue;}}
   if(q.cp){q.max_rr=max(q.max_rr,rr);if(rr<=0){q.be=1;q.end_rr=rr;q.done=1;q.endt=t;continue;}if(t-E.t>=60*60000LL){q.to60=1;q.end_rr=rr;q.done=1;q.endt=t;continue;}}
   aidx[w++]=id;}aidx.resize(w);prev=t;}}
 for(auto&q:s)if(!q.done){q.done=q.cens=1;}
 ofstream o("/mnt/data/runner_union_2024_path.csv");o<<"decision,S,dir,entry,censored,sl,timeout15,cp,cp_rr,max_rr,be,timeout60,end_rr,cp_ms,end_ms\n";for(size_t i=0;i<e.size();++i){auto&q=s[i];o<<e[i].ts<<","<<e[i].S<<","<<e[i].d<<","<<q.ep<<","<<q.cens<<","<<q.sl<<","<<q.to15<<","<<q.cp<<","<<q.cp_rr<<","<<q.max_rr<<","<<q.be<<","<<q.to60<<","<<q.end_rr<<","<<q.cpt<<","<<q.endt<<"\n";}
}
